from django.core.management.base import BaseCommand
from restaurant.models import MenuItem


class Command(BaseCommand):
    help = "Seed the database with sample menu items"

    def handle(self, *args, **kwargs):
        self.stdout.write("Seeding menu data...")

        MenuItem.objects.all().delete()

        items = [
            # Appetizers
            {
                "name": "Hummus Beiruti",
                "name_ar": "حمص بيروتي",
                "description": "Creamy chickpea dip with olive oil, paprika and fresh herbs",
                "description_ar": "حمص كريمي مع زيت الزيتون والفلفل الحلو والأعشاب الطازجة",
                "price": 25.00,
                "category": "appetizers",
                "is_featured": True,
                "spice_level": 0,
                "calories": 320,
                "prep_time": 10,
            },
            {
                "name": "Fattoush Salad",
                "name_ar": "سلطة فتوش",
                "description": "Fresh garden vegetables with toasted pita chips and sumac dressing",
                "description_ar": "خضروات طازجة مع قطع الخبز المحمص وصلصة السماق",
                "price": 22.00,
                "category": "appetizers",
                "is_featured": False,
                "spice_level": 0,
                "calories": 180,
                "prep_time": 10,
            },
            {
                "name": "Kibbeh",
                "name_ar": "كبة مقلية",
                "description": "Crispy fried bulgur wheat shells filled with seasoned minced lamb",
                "description_ar": "قشرة مقرمشة من البرغل محشوة باللحم المفروم المتبل",
                "price": 38.00,
                "category": "appetizers",
                "is_featured": True,
                "spice_level": 1,
                "calories": 420,
                "prep_time": 20,
            },
            {
                "name": "Sambousek",
                "name_ar": "سمبوسك",
                "description": "Golden pastry parcels filled with cheese and herbs",
                "description_ar": "معجنات ذهبية محشوة بالجبن والأعشاب",
                "price": 30.00,
                "category": "appetizers",
                "is_featured": False,
                "spice_level": 0,
                "calories": 380,
                "prep_time": 15,
            },
            {
                "name": "Mutabbaq",
                "name_ar": "مطبق",
                "description": "Spiced minced meat and egg stuffed in thin crispy pastry",
                "description_ar": "لحم مفروم متبل وبيض في عجينة رفيعة مقرمشة",
                "price": 35.00,
                "category": "appetizers",
                "is_featured": False,
                "spice_level": 1,
                "calories": 450,
                "prep_time": 20,
            },
            # Mains
            {
                "name": "Kabsa Al-Malek",
                "name_ar": "كبسة الملك",
                "description": "Royal spiced rice with slow-cooked whole lamb, roasted nuts and raisins",
                "description_ar": "أرز بالبهارات الملكية مع الخروف المطهو ببطء والمكسرات المحمصة والزبيب",
                "price": 145.00,
                "category": "mains",
                "is_featured": True,
                "spice_level": 2,
                "calories": 980,
                "prep_time": 90,
            },
            {
                "name": "Lamb Mandi",
                "name_ar": "مندي لحم",
                "description": "Tender slow-smoked lamb over fragrant basmati rice cooked in a traditional tandoor",
                "description_ar": "لحم الخروف الطري المدخن على أرز البسمتي العطري في التندور التقليدي",
                "price": 165.00,
                "category": "mains",
                "is_featured": True,
                "spice_level": 1,
                "calories": 1100,
                "prep_time": 120,
            },
            {
                "name": "Mixed Royal Grill",
                "name_ar": "مشاوي مشكلة ملكية",
                "description": "Premium selection of lamb chops, shish tawook, kofta and grilled prawns",
                "description_ar": "تشكيلة من أضلاع الخروف وشيش طاووق والكفتة والروبيان المشوي",
                "price": 220.00,
                "category": "mains",
                "is_featured": True,
                "spice_level": 1,
                "calories": 1350,
                "prep_time": 35,
            },
            {
                "name": "Seafood Platter",
                "name_ar": "طبق المأكولات البحرية",
                "description": "Daily catch of grilled fish, lobster, prawns and calamari with saffron rice",
                "description_ar": "صيد اليوم من السمك المشوي وجراد البحر والروبيان والكاليماري مع أرز الزعفران",
                "price": 280.00,
                "category": "mains",
                "is_featured": True,
                "spice_level": 0,
                "calories": 850,
                "prep_time": 40,
            },
            {
                "name": "Ouzi",
                "name_ar": "أوزي",
                "description": "Whole baby lamb stuffed with spiced rice, slow-roasted to perfection",
                "description_ar": "خروف حجل محشو بالأرز المتبل، محمص ببطء على درجة الكمال",
                "price": 350.00,
                "category": "mains",
                "is_featured": False,
                "spice_level": 2,
                "calories": 1500,
                "prep_time": 180,
            },
            # Desserts
            {
                "name": "Umm Ali",
                "name_ar": "أم علي",
                "description": "Traditional warm bread pudding with cream, mixed nuts and cinnamon",
                "description_ar": "بودينج الخبز الدافئ التقليدي بالكريمة والمكسرات المشكلة والقرفة",
                "price": 38.00,
                "category": "desserts",
                "is_featured": True,
                "spice_level": 0,
                "calories": 560,
                "prep_time": 20,
            },
            {
                "name": "Saffron Kunafa",
                "name_ar": "كنافة الزعفران",
                "description": "Classic shredded wheat pastry with clotted cream and orange blossom syrup",
                "description_ar": "كنافة كلاسيكية بالقشطة وشراب ماء الزهر",
                "price": 35.00,
                "category": "desserts",
                "is_featured": True,
                "spice_level": 0,
                "calories": 480,
                "prep_time": 15,
            },
            {
                "name": "Baklava Royale",
                "name_ar": "بقلاوة ملكية",
                "description": "Layers of crispy filo pastry with pistachio, honey and rosewater",
                "description_ar": "طبقات من العجين المقرمش بالفستق الحلبي والعسل وماء الورد",
                "price": 28.00,
                "category": "desserts",
                "is_featured": False,
                "spice_level": 0,
                "calories": 380,
                "prep_time": 10,
            },
            {
                "name": "Muhalabiya",
                "name_ar": "مهلبية",
                "description": "Silky rosewater milk pudding topped with pistachios and gold leaf",
                "description_ar": "حلوى الحليب الحريرية بماء الورد والفستق وورق الذهب",
                "price": 32.00,
                "category": "desserts",
                "is_featured": False,
                "spice_level": 0,
                "calories": 290,
                "prep_time": 5,
            },
            # Drinks
            {
                "name": "Arabic Coffee",
                "name_ar": "قهوة عربية",
                "description": "Traditional Saudi coffee with cardamom and saffron, served with dates",
                "description_ar": "قهوة سعودية تقليدية بالهيل والزعفران، تقدم مع التمر",
                "price": 18.00,
                "category": "drinks",
                "is_featured": True,
                "spice_level": 0,
                "calories": 45,
                "prep_time": 5,
            },
            {
                "name": "Moroccan Mint Tea",
                "name_ar": "شاي مغربي بالنعناع",
                "description": "Fresh brewed gunpowder green tea with spearmint and cane sugar",
                "description_ar": "شاي أخضر طازج بالنعناع وقصب السكر",
                "price": 15.00,
                "category": "drinks",
                "is_featured": False,
                "spice_level": 0,
                "calories": 60,
                "prep_time": 5,
            },
            {
                "name": "Fresh Pomegranate Juice",
                "name_ar": "عصير رمان طازج",
                "description": "Cold-pressed pomegranate with a hint of rose water",
                "description_ar": "رمان معصور على البارد مع لمسة من ماء الورد",
                "price": 22.00,
                "category": "drinks",
                "is_featured": True,
                "spice_level": 0,
                "calories": 135,
                "prep_time": 5,
            },
            {
                "name": "Jallab",
                "name_ar": "جلاب",
                "description": "Classic Levantine drink with grape juice, rose water and pine nuts",
                "description_ar": "مشروب شامي كلاسيكي بعصير العنب وماء الورد وحبوب الصنوبر",
                "price": 20.00,
                "category": "drinks",
                "is_featured": False,
                "spice_level": 0,
                "calories": 180,
                "prep_time": 5,
            },
        ]

        for item_data in items:
            MenuItem.objects.create(**item_data)

        self.stdout.write(
            self.style.SUCCESS(f"[OK] Successfully seeded {len(items)} menu items!")
        )
