# Generated by Django 5.2.11 on 2026-05-21 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالعربية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر (ريال)')),
                ('category', models.CharField(choices=[('appetizers', 'المقبلات | Appetizers'), ('mains', 'الأطباق الرئيسية | Main Courses'), ('desserts', 'الحلويات | Desserts'), ('drinks', 'المشروبات | Drinks')], max_length=50, verbose_name='الفئة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='الصورة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('spice_level', models.IntegerField(default=0, help_text='0 = بدون حرارة, 1 = خفيف, 2 = متوسط, 3 = حار', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='مستوى الحرارة (0-3)')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='السعرات الحرارية')),
                ('prep_time', models.IntegerField(blank=True, null=True, verbose_name='وقت التحضير (دقيقة)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عنصر القائمة | Menu Item',
                'verbose_name_plural': 'قائمة الطعام | Menu Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('date', models.DateField(verbose_name='تاريخ الحجز')),
                ('time', models.CharField(choices=[('12:00', '12:00 ظهراً'), ('12:30', '12:30 ظهراً'), ('13:00', '01:00 مساءً'), ('13:30', '01:30 مساءً'), ('14:00', '02:00 مساءً'), ('14:30', '02:30 مساءً'), ('15:00', '03:00 مساءً'), ('18:00', '06:00 مساءً'), ('18:30', '06:30 مساءً'), ('19:00', '07:00 مساءً'), ('19:30', '07:30 مساءً'), ('20:00', '08:00 مساءً'), ('20:30', '08:30 مساءً'), ('21:00', '09:00 مساءً'), ('21:30', '09:30 مساءً'), ('22:00', '10:00 مساءً'), ('22:30', '10:30 مساءً'), ('23:00', '11:00 مساءً')], max_length=10, verbose_name='وقت الحجز')),
                ('guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='عدد الأشخاص')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار | Pending'), ('confirmed', 'مؤكد | Confirmed'), ('cancelled', 'ملغي | Cancelled'), ('completed', 'مكتمل | Completed')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات خاصة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حجز | Reservation',
                'verbose_name_plural': 'الحجوزات | Reservations',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
